joint_names_order:
  - "joint_1"
  - "joint_2"
  - "joint_3"
  - "joint_4"
  - "joint_5"
  - "joint_6"

joint_max_vel:
  - 0.383012504350156  # Joint velocity value for joint_1
  - 0.37256670877697   # Joint velocity value for joint_2
  - 0.68942250783028   # Joint velocity value for joint_3
  - 0.602189591308619  # Joint velocity value for joint_4
  - 0.602189591308619  # Joint velocity value for joint_5
  - 1.05386470893922   # Joint velocity value for joint_6

joint_pos_limits_lower:
  - -2.617994  # Lower limit for joint_1
  - -1.047198  # Lower limit for joint_2
  - 0.3141593  # Lower limit for joint_3
  - -2.96706   # Lower limit for joint_4
  - -1.658063  # Lower limit for joint_5
  - -2.96706   # Lower limit for joint_6

joint_pos_limits_upper:
  - 2.617994  # Upper limit for j1
  - 2.617994  # Upper limit for j2
  - 2.443461  # Upper limit for j3
  - 2.96706  # Upper limit for j4
  - 2.356194  # Upper limit for j5
  - 2.96706  # Upper limit for j6

joint_trajectory_controller_command_topic: "/cobotta/arm_controller/command"
joint_states_topic: "/joint_states"

gello_start_joints:
  - 0.0  # joint_1
  - 0.0  # joint_2
  - !degrees 90.0  # joint_3
  - 0.0  # joint_4
  - !degrees 90.0  # joint_5
  - 0.0  # joint_6
  - 0.0  # gripper_finger_joint