default_hostname: "127.0.0.1"
default_robot_port: 6001
default_camera_port: 6002  # If there are multiple cameras, use consecutive numbers

agent_name: "gello" # "gello" or "act"
control_hz: 100
number_of_episodes: 1
number_of_steps: 1000