# operation config
default_hostname: "127.0.0.1"
default_robot_port: 6001
control_hz: 500
dynamixel_baudrate: 2000000

# camera config
default_camera_port: 7001 # If there are multiple cameras, use consecutive numbers
camera_names: ["base", "side"]
camera_width: 640
camera_height: 480
camera_fps: 60

# imitation learning config
task_name: "cup_push"
save_episode_dir: "/root/onolab/catkin_ws/src/gello_software/gello_ros/scripts/episode_data"
eval_ckpt_dir: "/root/onolab/catkin_ws/src/gello_software/gello_ros/scripts/checkpoints/20241202_185808_cup_push"
number_of_episodes: 5 # trials
number_of_steps: 10000 # steps for each episode
state_dim: 6
action_dim: 6
